apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datasci-ldap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - name: openldap
        image: osixia/openldap
        ports:
          - containerPort: 389
          - containerPort: 636
        env:
        - name: LDAP_ADMIN_PASSWORD
          value: "admin"
      - name: phpldapadmin
        image: osixia/phpldapadmin
        ports:
          - containerPort: 80
        # DN: cn=admin,dc=example,dc=org
        # password: admin
        env:
        - name: PHPLDAPADMIN_HTTPS
          value: "false"
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: localhost
---
apiVersion: v1
kind: Service
metadata:
  name: ldap
spec:
  ports:
  - name: ldap
    port: 389
    targetPort: 389
  - name: ldap-ssl
    port: 636
    targetPort: 636
  - name: ldap-admin
    port: 8888
    targetPort: 80
    protocol: TCP
  selector:
    app: ldap
  type: ClusterIP
