apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: flower
  name: flower
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/flower
spec:
  replicas: 1
  selector:
    matchLabels:
      run: flower
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: flower
    spec:
      containers:
      - command:
        - /entrypoint.sh
        - flower
        env:
        - name: EXECUTOR
          value: Celery
        image: puckel/docker-airflow:1.9.0-4
        imagePullPolicy: IfNotPresent
        name: flower
        ports:
        - containerPort: 5555
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
