apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: scheduler
  name: scheduler
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      run: scheduler
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: scheduler
    spec:
      containers:
      - command:
        - /entrypoint.sh
        - scheduler
        env:
        - name: LOAD_EX
          value: "n"
        - name: FERNET_KEY
          value: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - name: EXECUTOR
          value: Celery
        image: puckel/docker-airflow:1.9.0-4
        imagePullPolicy: IfNotPresent
        name: scheduler
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/airflow/dags
          name: dags-volume
      volumes:
      - name: dags-volume
        hostPath:
          path: /var/dags
          type: DirectoryOrCreate
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
