apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: webserver
  name: webserver
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      run: webserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: webserver
    spec:
      containers:
      - command:
        - /entrypoint.sh
        - webserver
        env:
        - name: LOAD_EX
          value: "n"
        - name: FERNET_KEY
          value: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - name: EXECUTOR
          value: Celery
        image: puckel/docker-airflow:1.9.0-4
        imagePullPolicy: IfNotPresent
        name: webserver
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/airflow/dags
          name: data-volume
          subPath: dags
      volumes:
      - name: data-volume
        gcePersistentDisk:
        pdName: data
        fsType: ext4
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
