apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: bastion
  name: bastion
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/bastion
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bastion
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: bastion
    spec:
      containers:
      - image: moul/sshportal:v1.8.0
        imagePullPolicy: IfNotPresent
        name: bastion
        ports:
        - containerPort: 2222
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}

