apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: worker
  name: worker
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/worker
spec:
  replicas: 1
  selector:
    matchLabels:
      run: worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: worker
    spec:
      containers:
      - env:
        - name: EXECUTOR
          value: Celery
        - name: USER_NAME
          value: ds
        - name: USER_PASSWORD
          value: ds
        - name: START_JUPYTERHUB
          value: "no"
        - name: START_RSTUDIO
          value: "no"
        - name: START_AIRFLOW
          value: "yes"
        image: anelen/datasci
        imagePullPolicy: Always
        name: worker
        volumeMounts:
        - mountPath: /usr/local/airflow
          name: dag-volume
        ports:
        - containerPort: 8793
          hostPort: 8793
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: dag-volume
        gitRepo:
          repository: "https://<some_token>@github.com/<your_org>/<your_repo>.git"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
