apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datasci-nfs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: datasci-nfs
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google-samples/nfs-server:1.1
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - name: gcepd
            mountPath: /exports
      volumes:
        - name: gcepd
          gcePersistentDisk:
            pdName: datasci-cluster-pd-1
            fsType: ext4
---
kind: Service
apiVersion: v1
metadata:
  name: datasci-nfs
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: datasci-nfs
