apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: suite
  name: suite
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/suite
spec:
  replicas: 1
  selector:
    matchLabels:
      run: suite
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: suite
    spec:
      containers:
      - env:
        - name: USER_NAME
          value: ds
        - name: USER_PASSWORD
          value: ds
        - name: START_JUPYTERHUB
          value: "yes"
        - name: START_RSTUDIO
          value: "yes"
        - name: START_AIRFLOW
          value: "no"
        image: anelen/datasci
        imagePullPolicy: Always
        name: suite
        ports:
        - containerPort: 22
          protocol: TCP
        - containerPort: 8000
          hostPort: 8000
          protocol: TCP
        - containerPort: 8787
          hostPort: 8787
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home
          name: suite-home
      volumes:
      - name: suite-home
        hostPath:
          path: /var/suite/home
          type: DirectoryOrCreate
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
