apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: webserver
  name: webserver
  selfLink: /api/v1/namespaces/default/services/webserver
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: webserver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
