apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: worker
  name: worker
  selfLink: /api/v1/namespaces/default/services/worker
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: port-1
    nodePort: 30001
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: port-2
    nodePort: 30787
    port: 8787
    protocol: TCP
    targetPort: 8787
  - name: port-3
    nodePort: 30793
    port: 8793
    protocol: TCP
    targetPort: 8793
  selector:
    run: worker
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
