apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: worker
  name: worker
  selfLink: /api/v1/namespaces/default/services/worker
spec:
  ports:
  - name: airflowworker
    port: 8793
    protocol: TCP
    targetPort: 8793
  selector:
    run: worker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
