apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: flower
  name: flower
  selfLink: /api/v1/namespaces/default/services/flower
spec:
  ports:
  - name: flower
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    run: flower
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
